version: '3.8' # Versão do Compose que está sendo utilizada

services:

  db: # Nome do serviço de banco de dados (MySQL)
    image: mysql:latest
    container_name: my-mysql-old
    ports:
      - "3308:3306"
    volumes:
      - "./.docker/mysql/dbdata:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
