version: '3.8' # Versão do Compose que está sendo utilizada

services:
  php: # Nome do serviço PHP
    image: php:7.4-apache
    container_name: meu-php-old
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www/Projeto/projeto-tarefa-cassum:/var/www/html
    links:
      - db

  db: # Nome do serviço de banco de dados (MySQL)
    image: mysql:latest
    container_name: my-mysql-old
    ports:
      - "3308:3306"
    volumes:
      - "/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
